/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:d879ea6b-c99b-446b-b72a-4315eacd15a6",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_xq9FMWGxz",
    "aws_user_pools_web_client_id": "fuo7h4o9ed0rgfsrb7hi25dla",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kk5amapuivc7fk2gprr7nirosq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dqqilkv55fablnllp5k4h3mine",
    "aws_user_files_s3_bucket": "notesappbucket112116-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
